images: golang:latest

stages:
   - build 
   - test
   - deploy to staging
   - docker


format:
    stage: test
    script:
      - go fmt $(go list ./.. | grep -v /vendor/) 
      - go vet $(go list ./.. | grep -v /vendor/)
      - go test -race $(go list ./.. | grep -v /vendor/)

compile:
    
    
    stage: build
    script: 
       - mkdir -p mybinaries
       - go build -0 mybinaries ./..
    artifacts:
       paths: 
