version: 2.1
orbs:
   docker: circleci/docker@1.5.0
executors:
  docker-publisher: 
            environment:
            #IMAGE_NAME: ocheotobo/backend:v1
            docker:
              - image: circleci/node:latest
                auth:
                  username: $DOCKERHUB_USER
                  password: $DOCKERHUB_PASS

jobs:
   Build:
     working_directory: ~/circleci-go
   
     docker: 
       - image: "circleci/golang"

     steps: 
       - checkout
       - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
       
       - run: 
            go mod download

       - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
    
   
   publish-docker-image:
    executors:
    steps:
         - checkout
         - setup_remote_docker
         - run:
           name: Publish docker image to docker hub
           command : |
             echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
             docker build . -t $IMAGE_NAME
             docker push ocheotobo/backend:v1



workflows:
  my-workflow: 
      jobs: 
         - Build
         - publish-docker-image:
                 filters: 
                     branches:
                       only: 
                         - main
                         

                          
         



